name: Scrape data

on:
  schedule:
    - cron:  "0 6 * * *"
  workflow_dispatch:
  push: {branches: [main]}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Scrape pool data
        run: |
          cd data
          pip3 install -r requirements.txt
          scrapy crawl chi_parks_pool_spider -O ../src/data/pools.json
      - uses: EndBug/add-and-commit@v9
        with:
          add: src/data/pools.json
          message: "Update pools data"
